version: '3.8'

services:
  app:
    build: .
    container_name: my-springboot-app
    ports:
      - "8080:8080"
    volumes:
      - ./mydatabase.db:/app/mydatabase.db  # Persist SQLite DB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/mydatabase.db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

        