version: '3'
services:
  cbr-api:
    build:
      context: .  # Use the current directory as build context
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    volumes:
      - ./data:/app/data  # Mount the data directory to persist data
    ports:
      - "8080:8080"

